//
//  HomeModels.swift
//  CekOngkir
//
//  Created by Indra Permana on 28/01/20.
//  Copyright (c) 2020 Yusuf Indra. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home
{
  // MARK: Use cases
  
    enum FetchRajaOngkir
    {
        struct Request
        {
        }
        struct Response
        {
            //        var provinces: [Province]
            var cities: [City]
        }
        struct ViewModel
        {
            //        struct displayedProvince {
            //            var province: String
            //        }
            struct displayedCity {
                var cityName: String
                var cityId: String
            }
            //        var displayedProvinces: [displayedProvince]
            var displayedCities: [displayedCity]
        }
    }
    
    struct QueryOngkirFormFields {
        var origin: String
        var destination: String
        var weight: Int
        var courier: String
    }
    enum QueryOngkir {
        struct Request {
            var queryOngkirFormFields: QueryOngkirFormFields
        }
        struct Response {
            var costs: [Costs]
        }
        struct ViewModel {
            struct displayedCost {
                var service: String
                var description: String
                var cost: Int
                var etd: String
            }
            var displayedCosts: [displayedCost]
        }
    }
    enum SaveToLocal {
        struct Request {
            var provinces: Province
            var city: City
        }
        struct Response {
            
        }
        struct ViewModel {
            
        }
    }
    
    enum PickerViewTag: Int {
        case OriginCityPickerView = 0
        case DestinationCityPickerView = 1
        case CourierPickerView = 2
    }
}
