//
//  HomeViewController.swift
//  CekOngkir
//
//  Created by Indra Permana on 28/01/20.
//  Copyright (c) 2020 Yusuf Indra. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeDisplayLogic: class
{
  func displaySomething(viewModel: Home.FetchRajaOngkir.ViewModel)
}

class HomeViewController: UIViewController, HomeDisplayLogic
{
  var interactor: HomeBusinessLogic?
  var router: (NSObjectProtocol & HomeRoutingLogic & HomeDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = HomeInteractor()
    let presenter = HomePresenter()
    let router = HomeRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
    override func viewWillAppear(_ animated: Bool) {
//        fetchProvincesApi()
//        fetchCitiesApi()
//        fetchProvincesLocal()
    }
  override func viewDidLoad()
  {
    super.viewDidLoad()
//    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
    func fetchProvincesApi() {
        let request = Home.FetchRajaOngkir.Request()
        interactor?.fetchProvincesRajaOngkirAPI(request: request)
    }
    func fetchProvincesLocal() {
        let request = Home.FetchRajaOngkir.Request()
        interactor?.fetchProvincesLocal(request: request)
    }
    
    func fetchCitiesApi() {
        let request = Home.FetchRajaOngkir.Request()
        interactor?.fetchCitiesRajaOngkirAPI(request: request)
    }
    func fetchCitiesLocal() {
        let request = Home.FetchRajaOngkir.Request()
//        interactor?.fetchCitiesLocal(request: request)
    }
//  func doSomething()
//  {
//    let request = Home.Something.Request()
//    interactor?.doSomething(request: request)
//  }
  
  func displaySomething(viewModel: Home.FetchRajaOngkir.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
